organization: illa
defaultSticker: clnbuq0zt55350il7di08vxey
stickers:
  -
    id: clnbuwccz20050il45drk120o
    alias: HACKTOBERFEST-ACCEPTED
  -
   id: clnbuz74g85880lkz0a5fyzis
   alias: HACKTOBERFEST-ACCEPTED-1
  -
    id: clnbv3uo903310fmgagvt713t
    alias: HACKTOBERFEST-ACCEPTED-2
  -
   id: clnbuq0zt55350il7di08vxey
   alias: HACKTOBERFEST-ACCEPTED-3
