organization: ILLA Cloud
defaultSticker: clnbuq0zt55350il7di08vxey
stickers:
  -
    id: clnbuwccz20050il45drk120o
    alias: This is a Digital badge you can earn by creating Apps or AI Agents with ILLA Cloud. 
  -
   id: clnbuz74g85880lkz0a5fyzis
   alias: This is a Digital badge you can earn by creating Apps or AI Agents with ILLA Cloud. 
  -
    id: clnbv3uo903310fmgagvt713t
    alias: This is a Digital badge you can earn by creating Apps or AI Agents with ILLA Cloud. 
  -
   id: clnbuq0zt55350il7di08vxey
   alias: This is a Digital badge you can earn by creating Apps or AI Agents with ILLA Cloud. 
