version: 2.1
jobs:
  build:
    working_directory: ~/project
    machine: # executor type
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Clone repo
          command: |
            git submodule init
            git submodule update
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/illa-builder-frontend.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /illa-builder-frontend.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=illa-builder-frontend -f Dockerfile -t illa-builder-frontend .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ./caches
            docker save -o ./caches/illa-builder-frontend.tar illa-builder-frontend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ./caches/illa-builder-frontend.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker tag illa-builder-frontend "illasoft/illa-builder-frontend:${CIRCLE_BRANCH}"
            docker push "illasoft/illa-builder-frontend:${CIRCLE_BRANCH}"
  deploy:
    machine: # executor type
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run:
          name: Download doctl & kubectl
          command: |
            sudo snap install doctl
            sudo snap install kubectl --classic
            doctl version
      - run:
          name: Setup kubectl
          command: |
            doctl auth init --access-token $DO_TOKEN
            mkdir -p /home/circleci/.kube
            sudo snap connect doctl:kube-config
            doctl kubernetes cluster kubeconfig save $DO_CLUSTER
            kubectl version
      - run:
          name: Download deploy yaml
          command: |
            git clone -b test $DEPLOY_REPO
            cd $DEPLOY_TEST_DIR
            kubectl delete pod -n test -l repo=illa-builder-frontend
            kubectl apply -f ./illa-builder-frontend/ -n test

workflows:
  illa-builder-frontend:
    when:
      or:
        - equal: [develop, << pipeline.git.branch >>]
    jobs:
      - build:
          context:
            - org-global
      - build:
          context:
            - org-global
          requires:
            - build
