name: jenkins-illa-builder-branch-chenxiaoyu
on:
  push:
    branches:
      - chenxiaoyu
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger chenxiaoyu build
        uses: appleboy/jenkins-action@master
        with:
          url: "http://ec2-13-230-170-106.ap-northeast-1.compute.amazonaws.com:9000/"
          user: "illasoft"
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "illa-builder-branch-chenxiaoyu"
