name: trigger jenkins job illa-builder-test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://ec2-18-181-186-207.ap-northeast-1.compute.amazonaws.com/"
        user: "illasoft"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "illa-builder-test"
